#%RAML 0.8
---
title: Niezbędnik Każdej Firmy
baseUri: http://tu_bedzie_uri/{version}
version: v1
mediaType: application/json
/vat:
    displayName: VAT
    get:
        description: Pobiera liste wszystkich wartości VATu
        responses:
            200:
                description: |
                    Zwraca listę wszystkich wartości VATu
                body:
                    schema: !include files/vat_get_response_schema.json
                    example: !include files/vat_get_response_example.json
    post:
        description: Dodaje nową stawkę VAT
        body:
            schema: !include files/vat_post_request_schema.json
            example: !include files/vat_post_request_example.json
        responses:
            201: 
                description: Udane tworzenie nowej stawki 
                body:
                    schema: !include files/vat_post_response_schema_201.json 
                    example: !include files/vat_post_response_example_201.json 
            400:
                description: Nie udało się utworzyć nowej stawki VAT
                body:
                    schema: !include files/vat_post_response_schema_400.json
                    example: !include files/vat_post_response_example_400.json
    /{vatID}:
        get:
            description: Pobiera wartość VATu o podanym id
            responses:
                200:
                    schema: !include files/vatid_get_response_schema_200.json
                    example: !include files/vatid_get_response_example_200.json
                404:
                    schema: !include files/vatid_get_response_schema_404.json
                    example: !include files/vatid_get_response_example_404.json
        put:
        delete:
/towar:
